name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            project: [Demo-ADC-Buzzer, Demo-RVMON, Demo-Tetris, Demo-Towers-Interactive, Demo-Towers, Demo-VGA, PlatformIO/RVPC]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install CH32V Platform
        run: pio pkg install -g -p "https://github.com/Community-PIO-CH32V/platform-ch32v.git"

      - name: Build Project
        run: cd SOFTWARE && cd ${{ matrix.project }} && pio run